# Generated by Django 4.2.4 on 2023-09-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlists",
            options={"verbose_name_plural": "Wishlists"},
        ),
    ]
